version: '2'
services:
  es:
    extends:
      file: common.yml
      service: common
    ports:
      - '9300:9300'
      - '9200:9200'
  es-test:
    extends:
      file: common.yml
      service: common
    ports:
      - '9350:9300'
      - '9250:9200'
  redis:
    image: redis
    ports:
      - '6379:6379'
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181